name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      custom-rendezvous:
        description: Use the custom rendezvous defaults (requires RS_PUB_KEY)
        type: boolean
        default: false
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      custom-rendezvous: ${{ github.event_name == 'workflow_dispatch' && inputs.custom-rendezvous }}
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
