name: Sync Fork
on:
  schedule:
    - cron: "0 0 23 * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          owner: rustdesk
          base: main
          head: master
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "nightly"
          tag_exists_error: false
          message: "nightly"
      - name: Tag already present (env)
        run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"
      - name: Tag already present (steps)
        run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"