name: Sync Fork
on:
  schedule:
    - cron: "0 0 23 * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          owner: rustdesk
          base: main
          head: master
