name: Sync Fork
on:
  schedule:
    - cron: "0 0 23 * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          owner: rustdesk
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: master
          head: master
          auto_approve: true
          retries: 2
          retry_after: 30
      - uses: tgymnich/fork-sync@v2
        with:
          owner: rustdesk
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: main
          head: master
          auto_approve: true
          retries: 2
          retry_after: 30
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "nightly"
          force_push_tag: true
          tag_exists_error: false
